---
title: "ALL STRINGS FOR STORAGE"
output: html_document
---

```{r}
strings_FRI <- c("Abnormal uterine bleeding", "Afterbirth pain", "Dysmenorrhoea", "Female reproductive tract disorder", "Female sex hormone level", "Female reproductive tract disorder", "Alpha 1 foetoprotein abnormal", "Heavy menstrual bleeding", "Intermenstrual bleeding", "Intra-uterine contraceptive device removal", "Menstrual disorder", "Menstruation delayed", "Menstruation irregular", "Premenstrual syndrome", "Abortion spontaneous", "Abortion spontaneous incomplete", "Uterine leiomyoma", "Uterine haemorrhage", "Uterine spasm", "Bradycardia foetal", "Biopsy foetal", "Bradycardia foetal", "Foetal cystic hygroma", "Foetal death", "Foetal exposure during pregnancy", "Foetal heart rate abnormal", "Foetal hypokinesia", "Foetal non-stress test abnormal", "Female sex hormone level", "Amenorrhoea", "Hypomenorrhoea", "Menopause", "Menorrhagia", "Oligomenorrhoea", "Polymenorrhoea", "Postmenopausal haemorrhage", "Postmenopause", "Vaginal discharge", "Vaginal disorder", "Vaginal erosion", "Vaginal haemorrhage", "Vaginal lesion", "Vaginal infection", "Vulvovaginal mycotic infection", "Vulval ulceration", "Vulval abscess", "Vulva cyst", "Cervix inflammation", "Adenocarcinoma of the cervix", "Cervix carcinoma", "Amniorrhoea", "Amniotic cavity infection", "Amniotic membrane rupture test positive", "Amniotic fluid index decreased")
```
```{r}
strings_eye <- c("Binocular eye movement disorder", "Conjunctival haemorrhage", "Conjunctival hyperaemia", "Conjunctivitis", "Conjunctivitis allergic", "Eye contusion", "Eye discharge", "Eye disorder", "Eye haemorrhage", "Eye infection", "Eye inflammation", "Eye irritation", "Eye movement disorder", "Eye pain", "Eye paraesthesia", "Eye pruritus", "Eye swelling", "Eyelid contusion", "Eyelid disorder", "Eyelid function disorder", "Eyelid irritation", "Eyelid mrgin crusting", "Eyelid oedema", "Eyelid ptosis", "Eyelid rash", "Eyelid sensory disorder", "Eyelids pruritis", "Nystagmus", "Ocular discomfort", "Ocular hyperaemia", "Ophthalmic herpes simplex", "Ophthalmological examination", "Ophthalmological examination abnormal", "Ocular icterus", "Pupil fixed", "Retinal haemorrhage", "Retinal vein occlusion", "Scleral disorder", "Scleritis", "Swelling of eyelid", "Vision blurred", "Visual acuity reduced", "Visual field defect", "Visual impairment", "Visual tracking test abnormal", "Vitreous detachment", "Vitreous floaters", "Uveitis")
#strings_eye
```
```{r}
strings_heart <- c("Angina pectoris", "Angina unstable", "Acute coronary syndrome", "Angioedema", "Angiogram abnormal", "Angiopathy", "Angiplasty", "Aortic arteriosclerosis", "Aortic valve calcification", "Aortic valve incompetence", "Arrhythmia", "Atelectasis", "Atrial tachycardia", "Arteriogram carotid abnormal", "Arteriogram coronary abnormal", "Arteriospasm coronary", "Arteriovenous fistula aneurysm", "Atrial enlargement", "Atrial flutter", "Atrial tachycardia", "Cardiac ablation", "Cardiac arrest", "Cardiac discomfort", "Cardiac disorder", "Cardiac failure chronic", "Cardiac failure congestive", "Cardiac flutter", "Cardiac monitoring abnormal", "Cardiac murmur", "Cardiac pademaker evaluation", "Cardiac stress test", "Cardiac telemetry abnormal", "Cardio-respiratory arrest", "Cardiogenic shock", "Cardiomegaly", "Cardiomyopathy", "Cardioversion", "Carotid arteriosclerosis", "Chest pain", "Coronary arterial stent insertion", "Coronary artery bypass", "Coronary artery disease", "Coronary artery occlusion", "Coronary artery stenosis", "Echocardiogram abnormal", "Electrocardiogram", "Electrocardiogram abnormal", "Electrocardiogram ambulatory", "Electrocardiogram ambulatory abnormal", "Electrocardiogram change", "Electrocardiogram PR prolongation", "Electrocardiogram PR shortened", "Electrocardiogram Q wave abnormal", "Electrocardiogram QRS complex abnormal", "Electrocardiogram QT prolonged", "Electrocardiogram ST segment abnormal", "Electrocardiogram ST segment depression", "Electrocardiogram ST segment elevation", "Endocarditis", "Electrocardiogram T wave abnormal", "Electrocardiogram T wave inversion", "Electrocardiogram T wave peaked", "Foetal heart rate abnormal", "Heart rate abnormal", "Heart rate decreased", "Heart rate increased", "Heart rate irregular", "Heart sounds abnormal", "Heart valve incompetence", "Hypertension", "Magnetic resonance imaging heart", "Microvascular coronary artery disease", "Myocardial infarction", "Myocardial necrosis marker", "Myocardial necrosis marker increased", "Myocardial strain", "Myocarditis", "Palpitations", "Pericardial effusion", "Pericarditis", "Right atrial dilatation", "Right ventricular dilatation", "Right ventricular dysfunction", "Right ventricular ejection fraction decreased", "Right ventricular hypertrophy", "Right ventricular systolic pressure decreased", "Scan myocardial perfusion", "Sinus arrhythmia", "Supraventricular extrasystoles", "Supraventricular tachycardia", "Tachycardia", "Vascular test", "Vasoconstriction", "Vasodilatation", "Vein discolouration", "Venogram abnormal", "Venous stent insertion", "Ventricular arrhythmia", "Ventricular extrasystoles", "Ventricular fibrillation", "Ventricular tachycardia") 
#strings_heart
strings_circulation_1 <- c("Abdominal wall haematoma", "Aneurysm", "Aneurysm ruptured", "Angioedema", "Angiogram cerebral", "Angiogram cerebral abnormal", "Angiogram pulmonary abnormal", "Angiopathy", "Angioplasty", "Arteriogram carotid abnormal", "Arteriogram coronary abnormal", "Arteriosclerosis", "Arteriosclerosis coronary artery", "Arteriospasm coronary", "Arteriovenous fistula aneurysm", "Basal ganglia haemorrhage", "Blood 1,25-dihydroxycholecalciferol decreased", "Blood albumin decreased", "Blood albumin increased", "Blood alkaline phosphatase increased", "Blood beta-D-glucan increased", "Blood beta-D-glucan positive", "Blood bicarbonate decreased", "Blood bicarbonate increased", "Blood bilirubin decreased", "Blood bilirubin increased", "Blood bilirubin unconjugated", "Blood calcium", "Blood calcium decreased", "Blood chloride decreased", "Blood chloride increased", "Blood cholesterol", "Blood cholesterol increased", "Blood cholesterol decreased", "Blood corticotrophin", "Blood count abnormal", "Blood creatine increased", "Blood creatine abnormal", "Blood creatine phosphokinase abnormal", "Blood creatine phosphokinase decreased", "Blood creatine phosphokinase increased", "Blood creatine phosphokinase MB decreased", "Blood creatine phosphokinase MB increased", "Blood creatinine decreased", "Blood creatinine increased", "Blood culture", "Blood culture positive", "Blood disorder", "Blood fibrinogen", "Blood fibrinogen increased", "Blood gases abnormal", "Blood glucose abnormal", "Blood ketone body increased", "Blood glucose decreased", "Blood glucose increased", "Blood insulin increased", "Blood lactate dehydrogenase", "Blood lactate dehydrogenase increased", "Blood lactic acid", "Blood lactic acid decreased", "Blood lactic acid increased", "Blood magnesium decreased", "Blood magnesium increased", "Blood methaemoglobin", "Blood osmolarity decreased", "Blood osmolarity increased", "Blood parathyroid hormone increased", "Blood pH increased", "Blood phosphorus", "Blood phosphorus decreased", "Blood phosphorus increased", "Blood potassium decreased", "Blood potassium increased", "Blood pressure abnormal", "Blood pressure decreased", "Blood pressure diastolic abnormal", "Blood pressure diastolic increased", "Blood pressure fluctuation", "Blood pressure immeasurable", "Blood pressure increased", "Blood pressure measurement", "Blood pressure orthostatic abnormal", "Blood pressure systolic", "Blood pressure systolic abnormal", "Blood pressure systolic decreased", "Blood pressure systolic increased", "Blood smear test abnormal", "Blood sodium decreased", "Blood sodium increased", "Blood test", "Blood test abnormal", "Blood thyroid stimulating hormone", "Blood thyroid stimulating hormone decreased", "Blood triglycerides increased", "Blood urea decreased", "Blood urea increased", "Blood urea nitrogen/creatinine ratio", "Blood urea nitrogen/creatinine ratio decreased", "Blood urea nitrogen/creatinine ratio increased", "Blood uric acid", "Blood uric acid increased", "Carboxyhaemoglobin decreased", "Cerebellar haemorrhage", "Cerebral haemorrhage")
#strings_circulation_1
strings_circulation_2 <- c("Cerebral microangiopathy", "Cerebral small vessel ischaemic disease", "Cerebral ventricle dilatation", "Cerebrovascular accident", "Circulatory collapse", "Conjunctival haemorrhage", "Cyanosis", "Deep vein thrombosis", "Dizziness", "Dizziness postural", "Exercise tolerance decreased", "Eye haemorrhage", "Fatigue", "Fibrin D dimer increased", "Full blood count abnormal", "Gastrointestinal haemorrhage", "Glycosylated haemoglobin", "Glycosylated haemoglobin decreased", "Glycosylated haemoglobin increased", "Haemarthrosis", "Haematemesis", "Haematochezia", "Haematocrit decreased", "Haematocrit increased", "Haematological malignancy", "Haematoma", "Haematoma muscle", "Haematuria", "Haemodialysis", "Haemodynamic instability", "Haemolysis", "Haemoptysis", "Haemorrhage in pregnancy", "Haemolytic anaemia", "Haemoglobin abnormal", "Haemoglobin decreased", "Haemoptysis", "Haemorrhage", "Haemorrhage intracranial", "Haemorrhagic stroke", "Hypoxic-ischaemic encephalopathy", "Injection site bruising", "Injection site extravasation", "Injection site haematoma", "Injection site haemorrhage", "Injection site streaking", "Internal haemorrhage", "Intra-abdominal haemorrhage", "Intracerebral haematoma evacuation", "Ischaemia", "Ischaemic cardiomyopathy", "Ischaemic stroke", "Lacunar infarction", "Mean cell haemoglobin concentration decreased", "Mean cell haemoglobin concentration increased", "Mean cell haemoglobin decreased", "Mean cell haemoglobin increased", "Microembolism", "NIH stroke scale abnormal",  "Rectal haemorrhage", "Skin haemorrhage", "Subarachnoid haemorrhage", "Subdural haematoma", "Subdural haemorrhage", "Occult blood", "Occult blood positive", "Oxygen saturation abnormal", "Oxygen saturation decreased", "Oxygen therapy", "Pallor", "Penile haemorrhage", "Peripheral vein occlusion", "Phlebitis", "Platelet count", "Platelet count decreased", "Platelet count increased", "Platelet transfusion", "Poor peripheral circulation", "Posthaemorrhagic hydrocephalus", "Presyncope", "Pulse abnormal", "Pulse absent", "Red blood cell count abnormal", "Red blood cell count decreased", "Red blood cell count increased", "Red blood cell nucleated morphology", "Red blood cell nucleated morphology present", "Red blood cell rouleaux formation present", "Red blood cell schistocytes", "Red blood cell schistocytes present", "Red blood cell sedimentation rate", "Red blood cell sedimentation rate increased", "Retinal haemorrhage", "Retinal vein occlusion", "Sensation of blood flow", "Swelling", "Syncope", "Transient ischaemic attack", "Troponin", "Troponin increased", "Troponin I", "Troponin I increased", "Troponin T increased", "Thrombosis", "Upper gastrointestinal haemorrhage", "Uterine haemorrhage", "Vaginal haemorrhage", "Vascular test", "Vasculitis", "Vasoconstriction", "Vasodilatation", "Vein discolouration", "Vein disorder", "Vein rupture", "Venogram", "Venogram abnormal", "Venous stent insertion")
#strings_circulation_2
strings_circulation <- c(strings_circulation_1,strings_circulation_2)
#strings_circulation
strings_respiration <- c("Acute respiratory distress syndrome", "Acute respiratory failure", "Airway secretion clearance therapy", "Allergic respiratory symptom", "Alveolar lung disease", "Atelectasis", "Bilevel positive airway pressure", "Biopsy lung abnormal", "Breath sounds", "Breath sounds abnormal", "Breath sounds absent", "Bronchial hyperreactivity", "Bronchial secretion retention", "Bronchial wall thickening", "Bronchiectasis", "Bronchitis", "Bronchoscopy", "Bronchoscopy abnormal", "Bronchospasm", "Cardio-respiratory distress", "Chronic respiratory failure", "Chest X-ray abnormal", "Chronic obstructive pulmonary disease", "Continuous positive airway pressure", "Cough", "Dependence on respirator", "Dependence on oxygen therapy", "Dyspnoea", "Dyspnoea exertional", "Fraction of inspired oxygen", "Increased bronchial secretion", "Increased viscosity of upper respiratory secretion", "Interstitial lung disease", "Irregular breathing", "Laryngotracheobronchoscopy", "Lower respiratory tract congestion", "Lower respiratory tract infection", "Lung consolidation", "Lung disorder", "Lung hyperinflation", "Lung infiltration", "Lung neoplasm malignant", "Lung abscess", "Lung carcinoma cell type unspecified stage IV", "Lung consolidation", "Lung disorder", "Lung hyperinflation", "Lung infiltration", "Lung opacity", "Lung neoplasm malignant",  "Oxygen saturation abnormal", "Oxygen saturation decreased", "Oxygen therapy", "Mouth breathing", "Painful respiration", "Pleural effusion", "Pleurisy", "Pleuritic pain", "Pneumonia", "Pneumonia aspiration", "Pneumonitis", "Pneumonitis chemical", "Productive cough", "PO2 decreased", "Pulmonary congestion", "Pulmonary embolism", "Pulmonary hilar enlargement", "Pulmonary hypertension", "Pulmonary imaging procedure abnormal", "Pulmonary infarction", "Pulmonary oedema", "Pulmonary pain", "Pulmonary vascular disorder", "Rales", "Respiration abnormal", "Respiratory acidosis", "Respiratory arrest", "Respiratory depression", "Respiratory disorder", "Respiratory distress", "Respiratory failure", "Respiratory rate", "Respiratory rate decreased", "Respiratory rate increased", "Respiratory symptom", "Respiratory syncytial virus test negative", "Respiratory tract congestion", "Respiratory tract infection", "Respiratory tract oedema", "Respiratory viral panel", "Upper respiratory tract irritation", "Use of accessory respiratory muscles", "Resuscitation", "Sputum abnormal", "Sputum culture", "Upper-airway cough syndrome", "Use of accessory respiratory muscles" ,"Wheezing", "Venous oxygen partial pressure", "Venous oxygen saturation decreased")
#strings_respiration
strings_cardiovascular <- c(strings_heart, strings_circulation, strings_respiration)
#strings_cardiovascular
strings_neurological_1 <- c("Acoustic neuritis", "Acute disseminated encephalomyelitis", "Acute motor-sensory axonal neuropathy", "Ageusia", "Agitation", "Anti-neuronal antibody", "Aphasia", "Aphonia", "Areflexia", "Hallucination, auditory", "Autonomic nervous system imbalance", "Balance disorder", "Basal ganglia haemorrhage", "Basal ganglia stroke", "Biopsy brain", "Biopsy brain abnormal", "Brachial plexus injury", "Brain herniation", "Brain injury", "Brain midline shift", "Brain natriuretic peptide", "Brain natriuretic peptide increased", "Brain abscess", "Brain oedema", "Central nervous system inflammation", "Central nervous system lesion", "Cerebral artery occlusion", "Cerebral artery stenosis", "Cerebral atrophy", "Cerebral disorder", "Cerebral haemorrhage", "Cerebral infarction", "Cerebral microangiopathy", "Cerebral small vessel ischaemic disease", "Cerebral venous sinus thrombosis", "Cerebral ventricle dilatation", "Cerebrovascular accident", "Cervical spinal stenosis", "Coma", "Coma scale abnormal", "Computerised tomogram head abnormal", "Confabulation", "Confusional state", "Cranial nerve disorder", "Cranial nerve paralysis", "Deafness neurosensory", "Decompressive craniectomy", "Dementia", "Demyelination", "Demyelinating polyneuropathy", "Dental paraesthesia", "Depressed level of consciousness", "Depression", "Disorientation", "Dissociation", "Dissociative disorder", "Disturbance in attention", "Dysaesthesia", "Dyskinesia", "Electroencephalogram abnormal", "Encephalitis", "Euphoric mood", "Extraocular muscle paresis", "Eye paraesthesia", "Facial paralysis", "Focal dyscognitive seizures", "IVth nerve paralysis", "VIth nerve paralysis", "Gait disturbance", "Gait inability", "Gaze palsy", "Generalised tonic-clonic seizure", "Guillain-Barre syndrome", "Hallucination", "Hallucination, auditory", "Hallucination, visual", "Halo vision", "Hand-eye coordination impaired", "Head discomfort", "Headache", "Hemiparaesthesia", "Hemiparaesthesia teeth", "Herpes zoster infection neurological", "Hyperaesthesia", "Hyperaesthesia teeth", "Hypoaesthesia", "Hypoaesthesia eye", "Hypoaesthesia oral", "Incoherent", "Injected limb mobility decreased", "Injection site hypoaesthesia", "Injection site movement impairment", "Injection site muscle weakness", "Injection site nerve damage", "Injection site pain", "Intranasal hypoaesthesia", "Laryngeal tremor", "Limb immobilisation", "Lumbar puncture abnormal", "Lumbar spinal stenosis", "Magnetic resonance imaging brain", "Magnetic resonance imaging brain abnormal", "Magnetic resonance imaging spinal abnormal", "May-Thurner syndrome", "Memory impairment")
#strings_neurological_1
strings_neurological_2 <- c( "Meningioma", "Mononeuropathy", "Motion sickness", "Motor dysfunction", "Multiple sclerosis relapse", "Muscle atrophy",  "Muscle contractions involuntary", "Muscle contracture",  "Muscle disorder", "Muscle spasms", "Muscle spasticity", "Muscle twitching", "Muscular weakness", "Myalgia", "N-terminal prohormone brain natriuretic peptide increased", "Nerve block", "Nerve compression", "Nerve conduction studies abnormal", "Nerve injury", "Nervous system disorder", "Neurologic neglect syndrome", "Neurological examination", "Neurological examination abnormal", "Neurological symptom", "Neuropathy peripheral", "Optic ischaemic neuropathy", "Pain", "Paraesthesia", "Paraesthesia ear", "Paraesthesia oral", "Paralysis", "Partial seizures", "Perfusion brain scan", "Perfusion brain scan abnormal", "Peripheral motor neuropathy", "Peripheral sensorimotor neuropathy", "Peroneal nerve palsy", "Pharyngeal hypoaesthesia", "Pharyngeal paraesthesia", "Phonophobia", "Photopsia", "Polyneuropathy", "Posterior reversible encephalopathy syndrome", "Posturing", "Prohormone brain natriuretic peptide", "Psychogenic seizure", "Pulseless electrical activity", "Pupil fixed", "Scan brain", "Seizure", "Seizure cluster", "Seizure like phenomena", "Self esteem decreased", "Sensation of foreign body", "Sensitive skin", "Sensory disturbance", "Sensory loss", "Sleep apnoea syndrome", "Sleep disorder", "Slow response to stimuli", "Slow speech", "Sluggishness", "Small fibre neuropathy", "Somnolence", "Speech disorder", "Speech sound disorder", "Spinal cord lipoma", "Spinal disorder", "Spinal osteoarthritis", "Spinal nerve stimulator implantation", "Spinal operation", "Spinal pain", "Spinal retrolisthesis", "Spinal stenosis", "Spinal X-ray abnormal", "Staring", "Subarachnoid haemorrhage", "Taste disorder", "Thinking abnormal", "Tinnitus", "Tongue biting", "Tongue movement disturbance", "Tongue spasm", "Tremor", "Tunnel vision", "Unresponsive to stimuli", "Upper motor neurone lesion", "Vertigo", "Vestibular neuronitis", "Vision blurred", "Visual acuity reduced", "Visual impairment", "Visual tracking test abnormal", "White matter lesion")
#strings_neurological_2
strings_neurological <- c(strings_neurological_1, strings_neurological_2)
#strings_neurological
strings_immunological_mediators <- c("Allergy test positive", "Allergy to vaccine", "Anaphylactic reaction", "Anaphylactic shock", "Anaphylactoid reaction", "Antibody test abnormal", "Antineutrophil cytoplasmic antibody", "Antineutrophil cytoplasmic antibodyincreased", "Antineutrophil cytoplasmic antibody positive", "Antinuclear antibody positive", "Antiphospholipid antibodies positive", "Autoantibody positive", "Band neutrophil count", "Band neutrophil percentage", "Band neutrophil percentage decreased", "Band neutrophil percentage increased", "Basophil count decreased", "Basophil count increased", "Basophil percentage decreased", "Basophil percentage increased", "Blood immunoglobulin A", "Blood immunoglobulin A decreased", "Blood immunoglobulin A increased", "Blood immunoglobulin E", "Blood immunoglobulin E decreased", "Blood immunoglobulin E increased", "Blood immunoglobulin G", "Blood immunoglobulin G increased", "Blood immunoglobulin M", "Blood immunoglobulin M decreased", "Blood immunoglobulin M increased", "CD4 lymphocyte percentage decreased", "CD4 lymphocytes", "C-reactive protein", "C-reactive protein decreased", "C-reactive protein increased", "Cardiolipin antibody negative", "Complement factor", "Complement factor C4", "CSF immunoglobulin G index", "CSF immunoglobulin increased", "CSF lymphocyte count abnormal", "CSF lymphocyte count increased", "CSF neutrophil count increased", "CSF white blood cell count increased", "Cytokine release syndrome", "Differential white blood cell count abnormal", "Drug hypersensitivity", "Drug reaction with eosinophilia and systemic symptoms", "Eczema", "Eosinophil count", "Eosinophil count decreased", "Eosinophil count increased", "Eosinophil percentage", "Eosinophil percentage decreased", "Eosinophil percentage increased", "Epstein-Barr virus antigen positive", "Haemophagocytic lymphohistiocytosis", "Hepatitis B antigen positive", "Hepatitis B surface antigen", "Hepatitis E antigen positive", "Histamine intolerance", "Histamine level increased", "Immature granulocyte count increased", "Immature granulocyte percentage increased", "Immune complex assay", "Immune system disorder", "Immune thrombocytopenia", "Immunisation", "Immunodeficiency", "Immunoglobulin therapy", "Immunoglobulins", "Immunology test", "Immunosuppression", "Inflammatory marker increased", "Interleukin level", "Leukocytosis", "Lip erythema", "Lymph node pain", "Lymph node palpable", "Lymphocyte count", "Lymphocyte count abnormal", "Lymphocyte count decreased", "Lymphocyte count increased", "Lymphocyte percentage decreased", "Lymphocyte percentage increased", "Monocyte count", "Monocyte count decreased", "Monocyte count increased", "Monocyte percentage decreased", "Monocyte percentage increased", "Neutrophil count", "Neutrophil count decreased", "Neutrophil count increased", "Neutrophil function test abnormal", "Neutrophil percentage decreased", "Neutrophil percentage increased", "Neutrophil toxic granulation present", "Neutrophilia", "Prostatic specific antigen increased", "Sputum abnormal", "Stress", "Systemic inflammatory response syndrome", "T-lymphocyte count", "T-lymphocyte count abnormal", "T-lymphocyte count decreased", "T-lymphocyte count increased", "Vaccine positive rechallenge", "White blood cell count", "White blood cell count abnormal", "White blood cell count decreased", "White blood cell count increased", "White blood cell morphology abnormal", "White blood cells urine positive")
#strings_immunological_mediators
strings_immune_effects <- c("Abdominal lymphadenopathy", "Acute febrile neutrophilic dermatosis", "Alopecia", "Anal erythema", "Anaphylactic reaction", "Anaphylactic shock", "Anaphylactoid reaction", "Anxiety", "Appendicitis", "Appendicitis perforated", "Arthralgia", "Arthritis", "Arthritis bacterial", "Asthma", "Autoimmune demyelinating disease", "Autoimmune disorder", "Autoimmune thyroiditis", "Bacterial tracheitis", "Bronchitis", "Bursitis", "Butterfly rash", "Cellulitis", "Cheilitis", "Cholecystitis", "Cholecystitis acute", "Cholecystitis chronic", "Cholecystitis infective", "Colitis", "Colitis ischaemic", "Complicated appendicitis", "Conjunctivitis", "Conjunctivitis allergic", "Cystitis", "Cytokine storm", "Dermatitis allergic", "Diabetes mellitus", "Diabetic ketoacidosis", "Diverticulitis", "Drug reaction with eosinophilia and systemic symptoms", "Dysgeusia", "Dysphagia", "Encephalomyelitis", "Eosinophilia", "Erythema", "Erythema multiforme", "Erythema nodosum", "Erythema of eyelid", "Gingival erythema", "Extensive swelling of vaccinated limb", "Eye inflammation", "Fasciitis", "Febrile convulsion", "Febrile neutropenia", "Focal peritonitis", "Hilar lymphadenopathy", "Guillain-Barre syndrome", "Hepatitis", "Hepatitis acute", "Herpes simplex", "Herpes simplex encephalitis", "Herpes simplex reactivation", "Herpes virus infection", "Herpes zoster", "Herpes zoster cutaneous disseminated", "Hidradenitis", "Hyperpyrexia", "Impaired driving ability", "Impaired work ability", "Immediate post-injection reaction", "Immune thrombocytopenia", "Inflammation", "Influenza A virus test positive", "Influenza like illness", "Influenza virus test positive", "Injection site abscess", "Injection site cellulitis", "Injection site discolouration", "Injection site discomfort", "Injection site erythema", "Injection site induration", "Injection site inflammation", "Injection site irritation", "Injection site joint pain", "Injection site joint swelling", "Injection site mass", "Injection site nodule", "Injection site oedema", "Injection site paraesthesia", "Injection site pruritus", "Injection site reaction", "Injection site swelling", "Injection site erythema", "Injection site lymphadenopathy",  "Iridocyclitis", "Labyrinthitis", "Laryngitis", "Leukopenia", "Lymphadenitis", "Lymphadenopathy", "Lymphadenopathy mediastinal", "Lymphoedema", "Lymphangitis", "Lymphopenia", "Malaise", "Mastitis", "May-Thurner syndrome", "Mediastinitis", "Meningitis", "Meningitis aseptic", "Meningitis viral", "Myelitis", "Mouth ulceration", "Mucosal inflammation", "Multiple allergies", "Multipathogen PCR test", "Multiple sclerosis relapse", "Mycoplasma test positive", "Myelitis transverse", "Nasopharyngitis", "Necrosis", "Neuritis", "Neutropenia", "Neutrophilia", "Nodular rash", "Noninfective encephalitis", "Noninfective gingivitis", "Ophthalmic herpes simplex", "Optic neuritis", "Oral herpes", "Oral mucosal blistering", "Oral viral infection", "Osteoarthritis", "Palindromic rheumatism", "Pancreatitis", "Pancreatitis acute", "Panophthalmitis", "Parkinsonism", "Peptostreptococcus infection", "Periarthritis", "Pharyngitis", "Poor quality sleep", "Pneumonia viral", "Pruritus", "Pyrexia", "Radiculitis brachial", "Rash", "Rash erythematous", "Rash macular", "Rash maculo-papular", "Rash morbilliform", "Rash papular", "Rash pruritic", "Reaction to excipient", "Reaction to previous exposure to any vaccine", "Rheumatoid arthritis", "Rhinitis", "Rosacea")
#strings_immunological_effects
strings_immune_system <- c(strings_immunological_mediators, strings_immune_effects)
strings_skin <- c("SARS-CoV-2 antibody test negative", "SARS-CoV-2 antibody test positive", "Scleritis", "Scrotal dermatitis", "Seasonal allergy", "Seborrhoea", "Secretion discharge", "Septic screen", "Serum sickness", "Spinal osteoarthritis", "Splenomegaly", "Sialoadenitis", "Sinusitis", "Splenic granuloma", "Staphylococcal bacteraemia", "Staphylococcal infection", "Staphylococcus test positive", "Status asthmaticus", "Stevens-Johnson syndrome", "Stomatitis", "Streptococcus test positive", "Synovitis", "Systemic lupus erythematosus", "Systemic lupus erythematosus rash", "Systemic scleroderma", "Tendonitis", "Tenosynovitis", "Thrombophlebitis", "Tongue erythema", "Tonsillitis", "Tracheitis", "Type III immune complex mediated reaction", "Ulnar neuritis", "Urosepsis", "Urticaria", "Uveitis", "Vaccination complication", "Vaccination site cellulitis", "Vaccination site erythema", "Vaginal ulceration", "Varicella zoster virus infection", "Vestibular neuronitis", "Viral cardiomyopathy", "Viral infection", "Viral pericarditis", "Viral rash", "Viral test positive", "Viral titre", "Vulvovaginal rash", "Acne", "Acute febrile neutrophilic dermatosis", "Biopsy skin", "Biopsy skin abnormal", "Blister", "Bullous haemorrhagic dermatosis", "Butterfly rash", "Cellulitis", "Chapped lips", "Contusion", "Dermatitis", "Dermatitis bullous", "Dermatitis contact", "Dermatitis exfoliative generalised", "Dry skin", "Exposure via skin contact", "Epidermal necrosis", "Eyelid rash", "Fungal infection", "Genital ulceration", "Hand dermatitis", "Haemorrhage subepidermal", "Herpes simplex", "Herpes simplex reactivation", "Herpes virus infection", "Herpes zoster", "Herpes zoster cutaneous disseminated", "Genital rash", "Increased tendency to bruise", "Injection site dryness", "Injection site hypersensitivity", "Injection site plaque", "Injection site rash", "Injection site scab", "Injection site urticaria", "Ischaemic skin ulcer", "Keratitis", "Lip blister", "Mouth ulceration", "Nail bed disorder", "Necrotising fasciitis", "Nipple pain", "Oedema mouth", "Oral contusion", "Oral herpes", "Oral mucosal blistering", "Oral viral infection", "Pain of skin", "Penile rash", "Petechiae", "Pruritus", "Psoriatic arthropathy", "Purpura", "Pustule", "Rash", "Rash erythematous", "Rash macular", "Rash maculo-papular", "Rash morbilliform", "Rash papular", "Rash pruritic", "Rash pustular", "Rash vesicular", "Rosacea", "Scab", "Scar", "Scratch", "Scrotal dermatitis", "Seborrhoea", "Sensitive skin", "Skin bacterial infection", "Skin burning sensation", "Skin culture", "Skin discolouration", "Skin discomfort", "Skin disorder", "Skin exfoliation", "Skin haemorrhage", "Skin hyperpigmentation", "Skin induration", "Skin irritation", "Skin odour abnormal", "Skin laceration", "Skin lesion", "Skin mass", "Skin plaque", "Skin reaction", "Skin sensitisation", "Skin swelling", "Skin tightness", "Skin test", "Skin test positive", "Skin tightness", "Skin ulcer", "Skin warm", "Systemic lupus erythematosus rash", "Systemic scleroderma", "Toxic epidermal necrolysis", "Ulcer", "Urticaria", "Vaccination site bruising", "Vaccination site irritation", "Vaccination site rash", "Viral rash", "Vulvovaginal rash", "Yellow skin")
#strings_skin
strings_temperature <- c("Body temperature", "Body temperature abnormal", "Body temperature decreased", "Body temperature increased", "Chills", "Cold sweat", "Exposure to extreme temperature", "Febrile neutropenia", "Feeling cold", "Feeling hot", "Feeling of body temperature change", "Flushing", "Hot flush", "Hyperpyrexia", "Hypothermia", "Injection site coldness", "Injection site warmth", "Night sweats", "Peripheral coldness", "Pyrexia", "Skin warm", "Temperature intolerance")
#strings_temperature
strings_immunological <- c(strings_immune_effects, strings_skin, strings_temperature)
#strings_immunological
```
```{r}
string_SAE_1 <- c("Abortion spontaneous", "Acute cardiac event", "Acute coronary syndrome", "Acute disseminated encephalomyelitis", "Acute left ventricular failure", "Acute monocytic leukaemia", "Acute motor-sensory axonal neuropathy", "Acute myeloid leukaemia", "Acute myocardial infarction", "Acute pulmonary oedema", "Acute respiratory distress syndrome", "Acute respiratory failure", "Administration site nerve damage", "Adrenal adenoma", "Adrenocortical insufficiency acute", "Adult failure to thrive", "Allodynia", "Alveolar lung disease", "Amyotrophic lateral sclerosis", "Anaphylactic reaction", "Anaphylactic shock", "Anaphylactoid reaction", "Aneurysm", "Aneurysm ruptured", "Angina pectoris", "Angina unstable", "Anuria", "Aortic aneurysm", "Aortic aneurysm rupture", "Aortic arteriosclerosis", "Aortic stenosis", "Aortic valve incompetence", "Aortic valve stenosis", "Appendicitis perforated", "Apraxia", "Arrhythmia", "Arteriogram carotid abnormal", "Arteriogram coronary abnormal", "Arteriosclerosis coronary artery", "Arteriovenous fistula aneurysm", "Atelectasis", "Atrial fibrillation", "Atrial septal defect", "Atrioventricular block", "Atrioventricular block first degree", "Atrioventricular block second degree", "Atypical pneumonia", "Autoimmune demyelinating disease", "Autopsy", "Axillary mass", "Bacteraemia", "Bacterial sepsis", "Basal ganglia haemorrhage", "Basal ganglia infarction", "Basal ganglia stroke", "Basilar artery occlusion", "Bedridden", "Bicytopenia", "Biopsy bone marrow abnormal", "Biopsy brain abnormal", "Biopsy lung abnormal", "Blindness", "Blood alkaline phosphatase increased", "Blood count abnormal", "Blood disorder", "Bone fragmentation", "Bone pain", "Brachial plexus injury", "Bradycardia", "Bradycardia foetal", "Bradykinesia", "Bradyphrenia", "Brain abscess", "Brain death", "Brain herniation", "Brain injury", "Brain midline shift", "Brain oedema", "Brain stem infarction", "Breath sounds abnormal", "Breath sounds absent", "Bronchial hyperreactivity", "Cardiac ablation", "Cardiac arrest", "Cardiac disorder", "Cardiac failure", "Cardiac failure acute", "Cardiac failure chronic", "Cardiac failure congestive", "Cardiac fibrillation", "Cardiac imaging procedure abnormal", "Cardiac monitoring abnormal", "Cardiac stress test abnormal", "Cardiac telemetry abnormal", "Cardio-respiratory arrest", "Cardio-respiratory distress", "Cardiogenic shock", "Cardiomegaly", "Cardiomyopathy", "Cardiovascular disorder", "Carotid arteriosclerosis", "Carotid artery occlusion", "Carotid pulse abnormal", "Catatonia", "Catheterisation cardiac", "Catheterisation cardiac abnormal", "Catheterisation venous", "Central cord syndrome", "Central nervous system inflammation", "Central nervous system lesion", "Cerebellar ataxia", "Cerebellar haemorrhage", "Cerebellar infarction", "Cerebellar stroke", "Cerebral arteriosclerosis", "Cerebral artery embolism", "Cerebral artery occlusion", "Cerebral artery stenosis", "Cerebral atrophy", "Cerebral disorder", "Cerebral haematoma", "Cerebral haemorrhage", "Cerebral infarction", "Cerebral ischaemia", "Cerebral microangiopathy", "Cerebral microhaemorrhage", "Cerebral small vessel ischaemic disease", "Cerebral venous sinus thrombosis", "Cerebral ventricle dilatation", "Cerebrovascular accident")
string_SAE_2 <- c("Cholangiocarcinoma", "Chronic obstructive pulmonary disease", "Chronic respiratory disease", "Chronic respiratory failure", "Circulatory collapse", "Colonoscopy abnormal", "Completed suicide", "Complex regional pain syndrome", "Complicated appendicitis", "Congenital anomaly", "Congestive cardiomyopathy", "Consciousness fluctuating", "Cor pulmonale", "Cor pulmonale acute", "Coronary artery thrombosis", "Cranial nerve injury", "Cranial nerve paralysis", "Craniocerebral injury", "Critical illness", "Cyanosis", "Cyclic vomiting syndrome", "Cytokine release syndrome", "Cytokine storm", "Deep vein thrombosis", "Defect conduction intraventricular", "Demyelinating polyneuropathy", "Demyelination", "Dependence on oxygen therapy", "Dependence on respirator", "Depersonalisation/derealisation disorder", "Diarrhoea haemorrhagic", "Diplegia", "Disseminated intravascular coagulation", "Diverticulitis intestinal perforated", "Diverticulum intestinal haemorrhagic", "Drug hypersensitivity", "Dysaesthesia", "Dysentery", "Dyskinesia", "Dyspnoea at rest", "Dyspnoea paroxysmal nocturnal", "Embolic cerebellar infarction", "Embolic cerebral infarction", "Embolic stroke", "Embolism", "Embolism venous", "Encephalitis", "Encephalomyelitis", "Encephalopathy", "End-tidal CO2 decreased", "Endocarditis", "Endotracheal intubation", "Endotracheal intubation complication", "Epidermal necrosis", "Face injury", "Facial neuralgia", "Facial paralysis", "Facial paresis", "Febrile convulsion", "Fine motor skill dysfunction", "Foetal death", "Foetal heart rate abnormal", "Foetal hypokinesia", "Generalised tonic-clonic seizure", "Haemorrhage intracranial", "Haemorrhagic stroke", "Death", "Heart rate abnormal", "Heart sounds abnormal", "Heart valve incompetence", "Hemiparesis", "Hepatic encephalopathy", "Hepatic vein thrombosis", "Hilar lymphadenopathy", "Hypercoagulation", "Hypertensive crisis", "Hypertensive emergency", "Hypertensive encephalopathy", "Hypertensive urgency", "Hypoxia", "Hypoxic-ischaemic encephalopathy", "Idiopathic intracranial hypertension", "Iliac vein occlusion", "Impaired self-care", "Impaired work ability", "Dyspnoea", "Internal haemorrhage", "Intestinal infarction", "Intra-abdominal haemorrhage", "Intracerebral haematoma evacuation", "Intracranial aneurysm", "Intracranial mass", "Intracranial pressure increased", "Intraductal papillary mucinous neoplasm", "Intraventricular haemorrhage", "Ischaemic cardiomyopathy", "Ischaemic stroke", "Lactic acidosis", "Lacunar infarction", "Lacunar stroke", "Left atrial dilatation", "Left atrial enlargement", "Left ventricular dysfunction", "Left ventricular end-diastolic pressure increased", "Left ventricular failure", "Left ventricular hypertrophy", "Leukocytosis", "Leukopenia", "Life support", "Loss of consciousness", "Loss of employment", "Loss of personal independence in daily activities", "Lower respiratory tract infection", "Lumbar puncture abnormal", "Lumbar spinal stenosis", "Lung abscess", "Lung hyperinflation", "Lung hypoinflation", "Lung infiltration", "Lung neoplasm malignant", "Lung opacity", "Magnetic resonance imaging brain abnormal", "Magnetic resonance imaging spinal abnormal", "Malignant nipple neoplasm female", "Mean platelet volume decreased", "Mean platelet volume increased", "Mechanical ventilation", "Medical induction of coma", "Meningioma", "Meningitis", "Meningitis aseptic", "Meningitis viral", "Mesenteric vein thrombosis")
string_SAE_3 <- c("Metabolic encephalopathy", "Metastases to bone", "Metastases to liver", "Microembolism", "Migraine", "Migraine with aura", "Mitral valve incompetence", "Mobility decreased", "Motor dysfunction", "Movement disorder", "Multiple organ dysfunction syndrome", "Multiple sclerosis relapse", "Muscle atrophy", "Muscle contractions involuntary", "Muscle contracture", "Muscle spasms", "Muscular weakness", "Musculoskeletal chest pain", "COVID-19", "Myelitis", "Myelitis transverse", "Myocardial infarction", "Myocardial ischaemia", "Myocardial necrosis marker increased", "Myocarditis", "Myosclerosis", "Asthenia", "Near death experience", "Necrosis", "Necrotising fasciitis", "Neoplasm malignant", "Nerve conduction studies abnormal", "Nerve injury", "Neuralgia", "Neuritis", "Neurological examination abnormal", "Neurological symptom", "Neuropathy peripheral", "NIH stroke scale abnormal", "Noninfective encephalitis", "Omental necrosis", "Ophthalmic artery thrombosis", "Ovarian necrosis", "Oxygen saturation decreased", "Oxygen therapy", "Packed red blood cell transfusion", "Painful respiration", "Pallor", "Palpitations", "Pancreatitis acute", "Paraesthesia", "Paralysis", "Partial seizures", "PCO2 decreased", "PCO2 increased", "Pelvic haemorrhage", "Pelvic venous thrombosis", "Penile haemorrhage", "Perfusion brain scan abnormal", "Pericarditis", "Peripheral motor neuropathy", "Peripheral nerve injury", "Peripheral nerve palsy", "Peripheral sensorimotor neuropathy", "Peripheral sensory neuropathy", "Peripheral vein occlusion", "Pharyngeal hypoaesthesia", "Pharyngeal paraesthesia", "Platelet aggregation decreased", "Platelet count abnormal", "Platelet count decreased", "Platelet count increased", "Pleural effusion", "Pleural thickening", "Pneumonia", "Pneumonia aspiration", "Pneumonia bacterial", "Pneumonia viral", "Pneumonitis", "Pneumonitis chemical", "Pneumothorax", "Portal vein thrombosis", "Posthaemorrhagic hydrocephalus", "Premature baby", "Premature delivery", "Premature labour", "Premature rupture of membranes", "Premature separation of placenta", "Preterm premature rupture of membranes", "Psychomotor hyperactivity", "Psychomotor skills impaired", "Pulmonary congestion", "Pulmonary embolism", "Pulmonary function test abnormal", "Pulmonary granuloma", "Pulmonary hilar enlargement", "Pulmonary hilum mass", "Pulmonary hypertension", "Pulmonary imaging procedure abnormal", "Pulmonary infarction", "Pulmonary mass", "Pulmonary oedema", "Pulmonary pain", "Pulmonary pneumatocele", "Pulmonary vascular disorder", "Pulse abnormal", "Pulse absent", "Pulseless electrical activity", "Radial pulse abnormal", "Reaction to excipient", "Reaction to preservatives", "Reaction to previous exposure to any vaccine", "Reactogenicity event", "Rectal haemorrhage", "Red blood cell count abnormal", "Renal embolism", "Renal failure", "Renal function test abnormal", "Respiration abnormal", "Respiratory acidosis", "Respiratory arrest", "Respiratory depression", "Respiratory disorder", "Respiratory distress")
string_SAE_4 <- c("Respiratory failure", "Respiratory rate", "Respiratory rate decreased", "Respiratory rate increased", "Respiratory symptom", "Respiratory tract congestion", "Respiratory tract infection", "Resuscitation", "Retinal artery occlusion", "Retinal artery thrombosis", "Retinal haemorrhage", "Retinal infarction", "Retinal ischaemia", "Retinal oedema", "Retinal tear", "Retinal vascular occlusion", "Retinal vein occlusion", "Retroperitoneal effusion", "Retroperitoneal oedema", "Rhabdomyolysis", "Right atrial dilatation", "Right ventricular dilatation", "Right ventricular dysfunction", "Right ventricular ejection fraction decreased", "Right ventricular hypertrophy", "Right ventricular systolic pressure decreased", "Ruptured cerebral aneurysm", "Sarcoidosis", "Scan with contrast abnormal", "Screaming", "Seizure", "Seizure cluster", "Seizure like phenomena", "Sepsis", "Septic encephalopathy", "Septic shock", "Shock", "Shock symptom", "Shoulder injury related to vaccine administration", "Silent myocardial infarction", "Sinus arrest", "Sinus arrhythmia", "Sinus bradycardia", "Sinus tachycardia", "Slow response to stimuli", "Spinal cord lipoma", "Spinal pain", "Spleen disorder", "Splenic infarction", "Staphylococcal sepsis", "Stiff person syndrome", "Stillbirth", "Subarachnoid haemorrhage", "Subdural haemorrhage", "Sudden cardiac death", "Sudden death", "Sudden hearing loss", "Sudden infant death syndrome", "Sudden visual loss", "Suicidal ideation", "Superinfection", "Superior sagittal sinus thrombosis", "Supraventricular extrasystoles", "Supraventricular tachycardia", "Surgery", "Suspected COVID-19", "Systemic inflammatory response syndrome", "Systemic lupus erythematosus rash", "Systolic hypertension", "Tachyarrhythmia", "Tachycardia", "Tachyphrenia", "Tachypnoea", "Terminal state", "Thalamic infarction", "Thinking abnormal", "Thrombotic stroke", "Tonic convulsion", "Toxic encephalopathy", "Toxic epidermal necrolysis", "Transient ischaemic attack", "Transverse sinus thrombosis", "Traumatic haemorrhage", "Troponin I increased", "Troponin increased", "Troponin T increased", "Type III immune complex mediated reaction", "Type IV hypersensitivity reaction", "Ulnar neuritis", "Ultrasound scan vagina abnormal", "Undifferentiated connective tissue disease", "Unresponsive to stimuli", "Upper motor neurone lesion", "Urinary bladder haemorrhage", "Urosepsis", "Use of accessory respiratory muscles", "Uterine contractions abnormal", "Vagus nerve disorder", "Vein rupture", "Vena cava embolism", "Venous oxygen saturation decreased", "Ventricular arrhythmia", "Ventricular extrasystoles", "Ventricular fibrillation", "Ventricular hypokinesia", "Ventricular tachycardia", "Vertebral artery occlusion", "Vertebral foraminal stenosis", "Vertebral lateral recess stenosis", "VIIIth nerve injury", "Visual impairment", "Vital functions abnormal", "VIth nerve paralysis", "Vitreous detachment", "Vocal cord paralysis", "Walking distance test abnormal", "Wall motion score index abnormal", "White matter lesion", "Withdrawal of life support")

strings_SAEs <- c(string_SAE_1, string_SAE_2, string_SAE_3, string_SAE_4)
#strings_SAEs
```
